version: '3'
services:
  lup-admin:
    container_name: lup-admin
    image: lup-admin
    environment:
      - API_URL=${API_URL}
      - IpFilterRules=${IpFilterRules}
      - RealIpFrom=${RealIpFrom}
#    depends_on:
#      - hub-api
    ports:
      - '8080:8080'
#  hub-api:
#    container_name: hub-api
#    image: hub-api
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Production    
#    ports:
#      - '8081:8080'
